### ISSUE TITLE
What code-pretifier do you use?

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#100]
Hi guys,

Out of curiosity, what CSS do you use to embellish your code snippets?

I've been playing with Google Code Prettify,  SyntaxHighligher and a couple of other more but I couldn't make them look the way I like; the one that gets close - if not exactly to what I'm looking for - is the one from GitHub but a requisite to use it is to previously create a _gist_ which depending on the content you want to publish sometimes isn't worth at all.

Yes, I use the ``` <blockquote> ``` tag for comments (I like how it's tweaked for __bashblog__) but I feel it neither fit the role for those small code snippets not worthy to gist.

Cheers

**Comment by cfenollosa** [comment]
If it's simple code, I just use `<code>` or `<blockquote>`. For more complex stuff, I upload it as a Gist and then embed it. You can see an example here: http://cfenollosa.com/blog/a-simple-script-to-postpone-your-own-email.html
