### ISSUE TITLE
<ol><li> breaks [Text](hyperlink) in Markdown

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#101]
![hand](https://cloud.githubusercontent.com/assets/394089/13059716/f64787a6-d40a-11e5-9ae4-2640b9b7ff70.png)

An ugly workaround would be to manually edit the .html file, which I prefer not to as that will make the process of editing the post _a bit_ awkward...

Suggestions?

**Comment by cfenollosa** [comment]
Did you try to just use Markdown's own lists? Is there any reason why they don't work in your situation and you need to mix HTML and Markdown?

We need to check if this is an issue with bashblog or the Markdown parser, I'm not sure that writing hacks to work around Markdown's bugs is a good idea.

**Comment by i90rr** [comment]
Well, the drive behind my request is that Markup is more flexible than Markdown; however after reading your comment I don't consider this issue worth the time and energy it would need - there are far more interesting stuff to hack into bashblog.

**Comment by cfenollosa** [comment]
In any case, maybe you could try using another markup parser, bashblog just feeds the text to it and reads the HTML output :)
