### ISSUE TITLE
Automated posting

### ISSUE THREAD

**Issue by mark-owen** [cfenollosa/bashblog#102]
Hi,

Is it possible to have the script parse an already generated file and post it without any need to use an editor (i.e without any human intervention) ?

For example: ./bashblog.sh post file.html

Thanks!

**Comment by Lex-2008** [comment]
i usually do a trick like this:

		EDITOR="cp file.html"
		echo 'p' | ./bashblog.sh post -html
		rm file.html

(you can also use markdown in this case)

**Comment by mark-owen** [comment]
This is exactly what I wanted, thank you.

**Comment by cfenollosa** [comment]
Thanks @Lex-2008, I added it to the wiki!
