### ISSUE TITLE
How to avoid having thousands of files in the home folder?

### ISSUE THREAD

**Issue by cfenollosa** [cfenollosa/bashblog#104]
I'm opening this discussion to everybody. As time passes, it is relatively easy for bashblog to place 100s of files in the root folder, 2x that if you use Markdown.

This is not bad per se, however, some filesystems start lagging when there are 1k-10k files in the same folder.

Do you think it would be interesting to have some sort of tree structure for posts, like the oldie `YYYY/MM/DD/post_name`? That has its drawbacks too; URLs are not so nice, and require a `RewriteRule` in `.htaccess` which is pretty bad for the web server's performance, probably even worsening the theoretical gain from not having thousands of files in the same folder.

I'm inclined to keep it as it is, however I'd like to hear more ideas on the matter. Thanks!

**Comment by Justin-Chaschowy** [comment]
Would the URL really be a big deal if it had a minimal date on it? I
wouldn't mind:

/0316/article-goes-here.html

**Comment by Lex-2008** [comment]
Maybe let's wait until it's a problem for anyone? I thought that
bashblog was never designed for people having thousands of posts, and
that blogs having so many posts usually use more advanced CMS.

-- 
If you can't read this email, please throw it away

**Comment by i90rr** [comment]
I'm in for implementing a method to bring order to the root directory, I don't enjoy the mess that it is having the posts mixed with _bashblog_'s own files (bb.sh, main.css, blog.css and tag files) - and I have just a bunch of posts.

May be @Lex-2008 is right, may be he is not but the fact is that I prefer bashblog over all the other static blog generators I researched and I would like to keep using it for the foreseeable future; so again it would be great to, for starters, begin ordering the way bashblog handles its own files and those related to the posts.

Cheers.

**Comment by cfenollosa** [comment]
Thanks for your feedback guys, I'll close the issue until this becomes a problem or somebody comes up with a nice solution.
