### ISSUE TITLE
When editing a post, dates and ordering change

### ISSUE THREAD

**Issue by CaptainKraft** [cfenollosa/bashblog#109]
If I use the edit command, the post is given the current date instead of keeping the original post date. Also, posts are put out of order.

When I ran the rebuild command, the posts went back to their correct order based on date.

**Comment by cfenollosa** [comment]
I can't replicate this. Editing a post using `./bb.sh edit post.html` keeps the file timestamp and the displayed date on the web site.

Which operating system are you using?

Thanks

**Comment by CaptainKraft** [comment]
Arch Linux

**Comment by cfenollosa** [comment]
Does the system drop any errors? This is super weird.
