### ISSUE TITLE
markdown check

### ISSUE THREAD

**Issue by hrmon** [cfenollosa/bashblog#111]
I think in bb.sh line 169 should be like this:
`[[ $("$markdown_bin" <<< $'line 1\n\nline 2') == $'<p>line 1</p>\n<p>line 2</p>' ]]`
not:
`[[ $("$markdown_bin" <<< $'line 1\n\nline 2') == $'<p>line 1</p>\n\n<p>line 2</p>' ]]'`

**Comment by McDutchie** [comment]
All the markdown scripts I've found output an empty line between paragraphs, so that needs two newline characters (\n). Is yours different? If so, the function needs to test for both cases. Please show me the output of the command:

    markdown <<< $'line 1\n\nline 2'

or

    Markdown.pl <<< $'line 1\n\nline 2'

**Comment by cfenollosa** [comment]
Indeed, I'm basing the test code in the original parser (Gruber's) so this behavior is expected.

If you use a different parser, you can change the test accordingly since you know what you're doing :)
