### ISSUE TITLE
"Please set your $EDITOR environment variable"

### ISSUE THREAD

**Issue by belvsdragon** [cfenollosa/bashblog#112]
It would be nice if there was a better explanation in the readme about setting the $EDITOR environment variable, because this was the first issue I ran into, when I executed bashblog. The only thing I found was 

> bashblog uses the $EDITOR environment value to open the text editor.

Additionally you could make a variable to set the editor in the config.

I solved the problem by setting the editor for the current session with `export EDITOR="/usr/bin/nano"`

**Comment by McDutchie** [comment]
I think it might be nice if, instead of simply printing an error message, bashblog prompted the user for an editor command to use, saving it to `.config`.
