### ISSUE TITLE
markdown.bash

### ISSUE THREAD

**Issue by vasyahacker** [cfenollosa/bashblog#119]
For the purity of an experiment, it is possible to [markdown.bash](https://github.com/chadbraunduin/markdown.bash)
.config:
`
markdown_bin=./markdown.sh
`

and bb.sh:
`-        [[ $("$markdown_bin" <<< $'line 1\n\nline 2') == $'<p>line 1</p>\n\n<p>line 2</p>' ]]`
`+        [[ $("$markdown_bin" <<< $'line 1\n\nline 2') == $'<p>\nline 1\n</p>\n\n<p>\nline 2\n</p>' ]]`

**Comment by cfenollosa** [comment]
Hi vasyahacker, thanks for the pointer.

I checked out that project, and unfortunately it isn't compatible with BSD sed:

    This script only works with GNU sed

This means that bashblog wouldn't support the BSD (and OSX) out of the box, which would break backwards compatibility.

I'm closing this issue, we can reopen it when they fix their compatibility. Thanks for your contribution!
