### ISSUE TITLE
bootstrap-ifying bashblog

### ISSUE THREAD

**Issue by thalios1973** [cfenollosa/bashblog#121]
Hi. I just started playing with bashblog. I love when folks use bash to solve "problems" like this. Bash just tends to make things so much more accessible to people. Anyway... I like it!

I was wondering if any work or experimentation has been done with getting this things bootstrap-ified? I see there is an old github pages branch, but that doesn't seem to be active. Just wondering. I may start hanging on this to see where I get ot.

**Comment by Justin-Chaschowy** [comment]
Hey Thalios

Not sure what you mean, could you go into more detail?

**Comment by thalios1973** [comment]
I'm just wondering if anyone has done any work on getting bashblog to be a bit more ready to work with Twitter bootstrap. I know there are custom headers and footers and such, so I guess things could just be wrapped around that. So it seems totally doable using the current version. I could just wrap the whole thing in a dev-container thingy, but not sure how one might make use of the the grid system for example. Again... I guess some well thought out header/footer work?

**Comment by thalios1973** [comment]
OK... now that I've actually dug into this I can see that my opening this "issue" was pointless. Sorry to have bothered.
