### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by JohnDarkhorse** [cfenollosa/bashblog#126]
I recently checked out bb.sh and have been running practice posts with it while configuring it.   Out of the blue, it throws this error:
$ bb.sh post
/usr/local/bin/bb.sh: line 2: $'\r': command not found
/usr/local/bin/bb.sh: line 7: $'\r': command not found
/usr/local/bin/bb.sh: line 10: $'\r': command not found
/usr/local/bin/bb.sh: line 15: $'\r': command not found
/usr/local/bin/bb.sh: line 18: syntax error near unexpected token `$'{\r''

'usr/local/bin/bb.sh: line 18: `global_variables() {
( the blank line is seen above because github kept wrapping the last line into the second to last )

It does this for both "post" and "edit".

I am not very good at shell scripting, but I can tell that line #2 of the script is empty & that the "unexpected token" is nowhere to be found in the bb.sh. 
I then grabbed a new copy of bb.sh ( in case I fumblefingered something ) and got the same error.
At that point, I made a new .config file with just the site title and still got the error.

Any help appreciated & thanks in advance

**Comment by i90rr** [comment]
Hi @JohnDarkhorse, can you reproduce the issue in a clean install? I'm not able to reproduce it with my  current .config file and just to be sure I downloaded latest bb.sh right now and it seems to be working fine:
```
~/git  rm -rf bashblog/
 ~/git  git clone https://github.com/cfenollosa/bashblog.git
Cloning into 'bashblog'...
remote: Counting objects: 855, done.
remote: Total 855 (delta 0), reused 0 (delta 0), pack-reused 855
Receiving objects: 100% (855/855), 793.64 KiB | 109.00 KiB/s, done.
Resolving deltas: 100% (280/280), done.
 ~/git  cd bashblog/                                                                                                                                                                                                                    12.7s
 ~/g/bashblog   master  ll
total 120
-rw-r--r--  1 i90rr  staff   9.2K Jan 25 15:29 README.md
-rwxr-xr-x  1 i90rr  staff    46K Jan 25 15:29 bb.sh
 ~/g/bashblog   master  ./bb.sh post
Please set your $EDITOR environment variable. For example, to use nano, add the line 'export EDITOR=nano' to your $HOME/.bashrc file
 ~/g/bashblog   master  set -xg EDITOR /Applications/Aquamacs.app/Contents/MacOS/bin/aquamacs
 ~/g/bashblog   master  ./bb.sh post
To preview the entry, open http://example.com/blog/title-on-this-line.html in your browser
[P]ost this entry, [E]dit again, [D]raft for later? (p/E/d)
```

**Comment by JohnDarkhorse** [comment]
If by "clean" you mean "without a config file", then yes a fresh pulled bb.sh and no .config produce the same error.

After starting this thread, I had a thought that something might be amiss with my bash / bash environment , which is looking more and more likely.

**Comment by JohnDarkhorse** [comment]
Am closing this, as I think it's an issue with my local system ( Cygwin ).  I installed bashblog on my remote webserver and it runs just fine.

Thanks for the help :)
