### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by skpy** [cfenollosa/bashblog#128]
I use pretty URLs (foo.com/first-post, foo.com/some-other-post) in my blog currently.  In pondering migrating to bashblog, I would like preserve these pretty URLs.

Other static site generators generate a directory for each post, and stick the post contents in the index.html file inside that directory.

I'd like to do the same with bashblog.  I'm happy to take a stab at supporting this; but if you want to beat me to it that's fine, too.  😀  If you want to point me in the right direction for the bits to change, I could work up a pull request even quicker.

**Comment by Natfan** [comment]
I would *love* redirect handling in `bashblog`. Maybe add the ability to have a `redirects.csv` that is formatted as such:

> oldFileName, newFileName

which would then autogenerate a `.htaccess` and update it upon blog rebuild?

Also maybe it could have a feature to do sitewide redirects like:

> *.html, *
> *-*.html, *_*.html

to remove the `.html` file extension at the end of the post, or to change hyphens in URLs to underscores?

My `bash` isn't really good enough to do any of this, and like @skpy said, I'd have no idea where to start, but I felt that I could add a few ideas to the table.

**Comment by aggsol** [comment]
This sounds a bit out og scop of bashblog, more like and additional script; something like pre- and post-build steps.

**Comment by cfenollosa** [comment]
Hi,

URL redirection is out of the scope of bashblog. You can achieve this using an `.htaccess` file or even softlinks in the filesystem. 

Thanks for the suggestion!
Carlos
