### ISSUE TITLE
Can bashblog create separate pages (like an 'About' page)?

### ISSUE THREAD

**Issue by kozross** [cfenollosa/bashblog#129]
I see that [on your blog][1] you have separate pages for 'About', 'Funny Papers', etc. Is this something bashblog is inherently capable of doing?

[1]: http://cfenollosa.com/blog/tag_bashblog.html

**Comment by cfenollosa** [comment]
Hi @kozross, you can add other html pages which are not tracked by bashblog: https://github.com/cfenollosa/bashblog/wiki/How-to-add-%22static%22-pages-which-are-ignored-by-bashblog

And if you want to share a common "navbar" for all of them, use a header or body template on bashblog:

https://github.com/cfenollosa/bashblog/wiki/How-to-set-a-personalized-header-or-body-on-each-page

Thanks for your interest!
