### ISSUE TITLE
Add option to use GNU Social for Comments

### ISSUE THREAD

**Issue by stormdragon2976** [cfenollosa/bashblog#130]
It would be great if we had a open source alternative to use for comments. would you consider adding the ability to automatically submit a new post to a GNU Social instance, then show all responses to it as the comments for the article?

**Comment by cfenollosa** [comment]
Hi,

Thanks for the suggestion! I don't think it will be useful to add in the main branch. Twitter and Disqus were implemented because they cover like 90% of the external comment sources but right now the code base is past 1000+ lines and I want it to stay minimal. Feel free to fork though!

Carlos
