### ISSUE TITLE
How to back date a blog post?

### ISSUE THREAD

**Issue by aggsol** [cfenollosa/bashblog#131]
I am moving old blog posts and sometimes I fix typos long afterwards but I want to keep the old date or force a specifc date. How can I do that?

**Comment by kshred** [comment]
Edit your published posts from the command line with the edit command.  That will keep your dates intact.

**Comment by aggsol** [comment]
But where in the markdown is the date set?

**Comment by kshred** [comment]
Nowhere. The date is generated by the blog so you never have to add a date yourself.  If you run ./bb.sh without any commands you'll get the manual which is short and pretty clear.

**Comment by aggsol** [comment]
After creating an old blog post I open it with
````
$ ./bb.sh edit -f entry.html
```
Then I edit the comment to
````

```
Then exectue a rebuild then it works!

**Comment by cfenollosa** [comment]
You shouldn't touch the generated files. Bashblog uses both the file creation date and an internal HTML tag to manage dates.

If you need to copy/move files to a different folder in the filesystem, please use `cp -a` which preserves the original file date.
