### ISSUE TITLE
When title and description are empty do not add to index.html

### ISSUE THREAD

**Issue by aggsol** [cfenollosa/bashblog#132]
The complete header is empty and should be skipped

```
<div class="headerholder"><div class="header">
<div id="title">
<h1 class="nomargin"><a class="ablack" href="http://example.com/index.html"></a></h1>
<div id="description"></div>
</div></div></div>
```

**Comment by cfenollosa** [comment]
Why would you want to have an empty title and description? It seems like a user issue. Not that there shouldn't be safeguards in the code, but I don't understand the use case. Could you elaborate?

**Comment by aggsol** [comment]
I want to style the title part myself and use a  'body.begin.template' for it. Now I just use `display:none`  to make the whole `headerholder` disappear. It has the same effect.

**Comment by cfenollosa** [comment]
Thanks, now I understand. This seems to be a very specific use case which would break backwards compatibility. I'm happy that you could solve it using CSS!
