### ISSUE TITLE
No support / discussion forum available

### ISSUE THREAD

**Issue by JohnDarkhorse** [cfenollosa/bashblog#137]
I have many issues I'd like to bring up, but are technically not "software issues" so do not belong here.

Is there a discussion / support forum somewhere for bashblog?

**Comment by aggsol** [comment]
I vote for bringing them here. With a label "discussion" I fell fine having discussions in the issues.

**Comment by Justin-Chaschowy** [comment]
I'd be interested in more discussions. I really love bashblog. Feel free.

**Comment by cfenollosa** [comment]
Feel free to use the `discussion` tag here :)
