### ISSUE TITLE
Correct scaling for mobile devices

### ISSUE THREAD

**Issue by bkauler** [cfenollosa/bashblog#140]
In this line:

`        echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />'`

I suggest to remove ", initial-scale=1.0"

It prevents the blog from scaling correctly on mobile devices. If you look at my bashblog and compare with others, you will see mine comes up immediately scaled to fit the screen width. The others, you have to use your fingers to get it right.

I know that ", initial-scale=1.0" is advised all over the place, but try for yourself, compare my blog with others, then try it on your blog.

Note, if your blog is designed as, say, 800 pixels wide, you can put "width=800", this will have the same effect as "width=device-width".

My blog:

<http://easyos.info/news/>

**Comment by aggsol** [comment]
You should not design your blog in Pixels as pixel density may vary. Initial scale as 1.0 is the proper way to go and set the appearance with CSS.
