### ISSUE TITLE
makeblog gui frontend for bashblog

### ISSUE THREAD

**Issue by wiake** [cfenollosa/bashblog#146]
Not an issue as such. I wondered if bashblog is still being actively developed?

Also wish to announce I have created a gui for bashblog, called "makeblog" (albeit providing some extra functionality on the fly). Temporarily, download and info here:

http://www.murga-linux.com/puppy/viewtopic.php?p=973642

Tested on DebianDog (Puppy Linux murga forum) mainly, but should work on any Debian/Ubuntu or a Puppy Linux system, as long as gtkdialog installed (link to a deb for that provided in above info). I may add alternative gui's later (e.g. maybe a yad version).

Unfortunately, makeblog currently uses GNU sed (since uses sed -i), so maybe won't work on MAC systems by default, but I may also look into changing that GNU sed need later.

wiak

**Comment by IBPX** [comment]
macOS uses BSD sed, which does support -i. However, I don't think there is a way to get gtkdialog running.

It seems the tar is corrupted. Would you upload the source to GitHub (or another VCS site) and apply a license if you haven't already?

**Comment by wiake** [comment]
The source code for gtkdialog (presuming that is what you mean) can be found here:

[https://github.com/01micko/gtkdialog](url)

**Comment by IBPX** [comment]
Thanks. I was referring to the source for makeblog, but I should have worded that better. It seems the tar for makeblog is corrupted, rather than gtkdialog.

**Comment by wiake** [comment]
As it says in the makeblog download:

> Just remove the dummy tar and follow the instructions above

i.e. It isn't a tar file. It just has a dummy tar extension because the murga puppy forum doesn't accept uploads without the tar extension. Just remove the extension and you will find that makeblog is a bash script. You can use it from the commandline without gtkdialog even - just enter ./makeblog -u for some usage help.

wiak

**Comment by IBPX** [comment]
Ah, okay. I didn't read that closely enough. Thanks.
