### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by Unip0rn** [cfenollosa/bashblog#152]
currently e.g. analytics and twitter stuff is being loaded without prior consent of the visitor.
If noone is faster I will write a piece of JS that will insert these parts on consent. 
This might unfortunatly break compability.

**Comment by Unip0rn** [comment]
Also I had been thinking about autogenerating some privacy policy but I guess that fails since you can't know what ```$global_analytics``` will do and therefor the effort would bring more complexity to the issue than it would help.

**Comment by aggsol** [comment]
That won't work as local laws would require different standards on privacy statements, disclaimers, imprints etc. Those should be treated as static files and written by the user itself. Also the JS loaded from elsewhere should handle that. IMO that is out of scope for bashblog.

**Comment by Unip0rn** [comment]
The part about different standards is a quite good argument. But I think no matter if it is in the scope - it becomes the responsibility of the one using bashblog and therefor there should be features to suppert this.

**Comment by Unip0rn** [comment]
I just realized this should rather be an issue with any script that gets included than of bashblog. Also this seems to be more or less your point? However since I as the initial reporter will close since there was noone else backing it.
