### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by xiamuguizhi** [cfenollosa/bashblog#154]
Please set your $EDITOR environment variable. For example, to use nano, add the line 'export EDITOR=nano' to your $HOME/.bashrc fil

**Comment by Unip0rn** [comment]
As you can read in the section "Configuration" from the README.md. The need for the user to set this variable is documented behaviour, so I guess I am missing your point somehow?

**Comment by Dahlis** [comment]
Have added the export EDITOR=nano in my $HOME/.bashrc file. Still gives me this error, or am I doing something wrong here?

**Comment by alfredbuehler** [comment]
What error? Did you `source ~/.bashrc` again?

**Comment by Dahlis** [comment]
When I do source ~/.bashrc nothing special happens. 
Tried different kind of things, when I have been googling about 'editor bashrc'. Nothing helps.
Using Ubuntu Server 19.10.

Here is a video, hopes this helps.
http://d.x64.re/upload/wXAZdUARio.mp4

**Comment by danielhjames** [comment]
Thanks for the update @Dahlis, I think this ticket could be closed now.
