### ISSUE TITLE
Are footnotes planned?

### ISSUE THREAD

**Issue by MAWSpitau** [cfenollosa/bashblog#163]
Hi there, 

thanks for that great piece of software. Is it planned, to be able to use footnotes?

`^[This is a Footnote]`
or 
`[^note]
[^note]: This is the footnote.
`

**Comment by Unip0rn** [comment]
That would be a feature of the markdown parser. If Markdown.pl  does not support it you might want to look into replacing it with some little script using pandoc. If you have results regarding that they might find a place in the documentation (if not here I will gladly include them in my fork).

**Comment by MAWSpitau** [comment]
Ah. Got it! 

I will think about it, but I think that is not my competence. ;)
