### ISSUE TITLE
Any interest in a better editing function?

### ISSUE THREAD

**Issue by Justin-Chaschowy** [cfenollosa/bashblog#81]
Specifically making it easier to choose which post you'd like to edit.

My solution was that when you chose the edit option, a list of all the available posts would be listed, and you could choose one by the corresponding #number beside each listing. 

Rather than having to type out the entire filename which is tedious.

**Comment by cfenollosa** [comment]
In unix tools this behavior is very common and personally, with tab-completion, I think the easiest way to select a post is to write the filename in the command line.
