### ISSUE TITLE
./bb.sh rebuild overwrites index.html --> should work for $index_file

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#86]

**Comment by cfenollosa** [comment]
Hi, could you provide more info? In no place in the code is `index.html` hardcoded. The `rebuild_index` function operates on `$index_file`

**Comment by cfenollosa** [comment]
Ok, this is related to #88 

All html files are treated by bashblog as blogposts, except

- Those defined as `$index_file`, `$header_file`, etc
- Those in `$html_exclude`

For your use case, you should probably add "index.html" to the `$html_exclude` list, that should do the trick.
