### ISSUE TITLE
When $index_file != index.html, index.html is indexed as another entry

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#88]
Please check attached screenshots:
![index_html_1](https://cloud.githubusercontent.com/assets/394089/12438325/7d943ce8-bf04-11e5-8000-13e394f22a53.png)
![index_html_2](https://cloud.githubusercontent.com/assets/394089/12438326/7d94a19c-bf04-11e5-97c3-9d98596586e8.png)

**Comment by cfenollosa** [comment]
You should add index.html to `$html_exclude` as explained in #86. Thanks for your feedback.
