### ISSUE TITLE
Ability to Set Meta Tags in Head

### ISSUE THREAD

**Issue by beardog108** [cfenollosa/bashblog#89]
For SEO and social media purposes, it would be great to be able to set the page description at least.

**Comment by cfenollosa** [comment]
Hi, you can do this as follows:

1. Create a file named (for example) `.header.template` in your blog folder
2. Edit it to include your whole head items, from `<!DOCTYPE html>`, meta tags, etc. Bashblog will append the `<title>` and `</head>` automatically, don't include them!
3. Include in your `.config` file the line `header_file=".header.template"`
4. Run `bb.sh rebuild` if necessary

**Comment by cfenollosa** [comment]
I included a guide in the wiki. Thanks for your question

https://github.com/cfenollosa/bashblog/wiki/How-to-set-a-personalized-header

**Comment by beardog108** [comment]
Hey,
Some meta tags such as 'description' are unqiue per page, unless I completely don't understand, this is not possible with the header file system without manually editing files outside of the bashblog context.

Thanks

**Comment by cfenollosa** [comment]
Ok, I think I now understand you.
There is a per-page personalized header function, currently used for custom Twitter cards: `twitter_card()`. You can easily add another `echo` for new meta tags, and it already has as a parameters the post file and the post title.

If you could specify a bit more the tags you need to append, maybe we can add them as default. Thanks!

**Comment by beardog108** [comment]
I will do that for my bashblog copy.
The only other meta tag that would be unique per page that i can think of is the 'keywords' tag.

Thanks for creating this awesome script
