### ISSUE TITLE
fail to set date when finishing to edit a post

### ISSUE THREAD

**Issue by anabis** [cfenollosa/bashblog#90]
On *NetBSD* with *ksh* after editing a post and closing nano (or your editor) here is the output : 
**date: unknown option -- f**
**Usage: date [-ajnu] [-d date] [-r seconds] [+format] [[[[[[CC]yy]mm]dd]HH]MM[.SS]]**
Posted 158.html
Rebuilding tag pages .
Rebuilding the index ....
Creating an index page with all the posts ....
Creating an index page with all the tags ...
Making RSS ....

**Comment by anabis** [comment]
At lines 1081 and 1084 I've tried to add '+' in front of the date format but then the error turn into something else so i gave up.

**Comment by anabis** [comment]
NetBSD is the problem, I workaround by sshfs'ing from GNU/Linux and running bb.sh from there.

**Comment by cfenollosa** [comment]
Yes, that's because either `bash` is aliased to `ksh`, or NetBSD doesn't recognize the shebang:
`#!/usr/bin/env bash`
