### ISSUE TITLE
iconv translit issue on netbsd

### ISSUE THREAD

**Issue by anabis** [cfenollosa/bashblog#91]
GNU iconv supports "ASCII//TRANSLIT", but not all other iconv implementations do. In particular, NetBSD's one doesn't.
I just removed "//translit" to fix the problem.

**Comment by cfenollosa** [comment]
Thanks for your feedback, I'll add a workaround similar to what we do with GNU's `date`. Expect a fix in a few days!

**Comment by cfenollosa** [comment]
Hi, I just tested it with OpenBSD and it's using GNU's iconv too. Could you paste your iconv's version, please? Maybe I can parse it to change options on the fly.

```
openbsd$ iconv --version
iconv (GNU libiconv 1.14)
Copyright (C) 2000-2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Bruno Haible
```
