### ISSUE TITLE
Non blog post pages

### ISSUE THREAD

**Issue by microspino** [cfenollosa/bashblog#92]
Which is the proper way to build content that is **not** a blog post with bashblog? 
_(I would call'em **static pages** although this doesn't make any sense when everything is static :) )_

**Comment by cfenollosa** [comment]
They're currently not supported, though it shouldn't be difficult to make a patch to accept a string of filenames which the script recognizes as "special" and doesn't index them on the home page.

I'll keep this issue opened for future work, thanks for your feedback

**Comment by platschi** [comment]
+1 for this feature.

**Comment by exitnode** [comment]
+1

**Comment by Justin-Chaschowy** [comment]
I don't understand why this is hard to do. It's very easy when it's a static blog like this.

Just copy your index.html file and rename it to my-services.htm and add a link in your nagivation.

**Comment by cfenollosa** [comment]
I guess the problem is that these pages get added to the index page when rebuilding.

I'll have some time in the next days to implement this, thanks for the feedback!

**Comment by Justin-Chaschowy** [comment]
Yeah I noticed that it did that.
The solution I came up with though was simple, just rename the pages with .htm instead of .html and the rebuild won't crawl em.

**Comment by cfenollosa** [comment]
Feature added, thanks for your feedback.

More info in [this wiki page](https://github.com/cfenollosa/bashblog/wiki/How-to-add-%22static%22-pages-which-are-ignored-by-bashblog)
