### ISSUE TITLE
Blog post order borked :'(

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#95]
Is there a way to force a reordering of the blog posts manually?

**Comment by i90rr** [comment]
So as per:
```bash
# Displays a list of the posts
list_posts() {
    ls ./*.html &> /dev/null
    (($? != 0)) && echo "No posts yet. Use 'bb.sh post' to create one" && return

    lines=""
    n=1
    while IFS='' read -r i; do
        is_boilerplate_file "$i" && continue
        line="$n # $(get_post_title "$i") # $(LC_ALL=$date_locale date -r "$i" +"$date_format")"
        lines+=$line\\n
        n=$(( n + 1 ))
    done < <(ls -t ./*.html)

    echo -e "$lines" | column -t -s "#"
}
```
The order of the posts is controlled by the time stamp, that explains the weird reordering that happens sometimes after adding a new post or doing a rebuild.

Wouldn't be more robust to add a *true* tracking function like assigning a distinct index number to each post?

**Comment by cfenollosa** [comment]
Let's discuss this on #96
