### ISSUE TITLE
bashblog shouldn't rely on file date for post ordering

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#96]
May be it would be best to store posts' index + date on a separate index tree.

**Comment by i90rr** [comment]
A workaround could be:
1) Store .md and .html files time stamp,
2) Do the rebuild magic
3) Touch -d $original_timestamp -m ***file***

**Comment by i90rr** [comment]
Just changed the name of the ticket as this has nothing to be with the 'build' command.

These are however valid scenarios when the time stamps of the posts are updated - thus messing with the blog contents:
1) When reverting a commit (git revert, git reset, etc.)
2) When cloning the ___user___.github.io repo

**Comment by cfenollosa** [comment]
Well, this is a design decision. There are two alternatives, the first one is to continue as-is, and the second one is to store the post date somewhere inside the file.

The post date is already stored inside the `<div class="subtitle">` for each file, though it doesn't contain the time by default, just the day, month and year.

Ordering files by timestamp is super convenient and fast and I'd like to keep it that was as much as possible. However, I understand that there are some scenarios which change timestamps and thus break ordering.

A middle ground solution could be to add a post timestamp to each file, inside a comment, and add a new `bb.sh regenerate_timestamps` to fix these after they have been modified externally.

What do you think of this solution? Let's try to find a good solution that can work for the future before starting coding :)

**Comment by i90rr** [comment]
Hi Carlos,
**+1**
That would be really useful, I'm very happy with the idea!

**Comment by cfenollosa** [comment]
Some more on this issue here: https://github.com/cfenollosa/bashblog/wiki/Regarding-file-timestamps-and-blogpost-dates

**Comment by i90rr** [comment]
Grrrreat, now I can clone my blog on the different computers I work daily and blog from them all - thanks!
