### ISSUE TITLE
Multiple Authors

### ISSUE THREAD

**Issue by virtualdxs** [cfenollosa/bashblog#99]
As far as I can tell, there's not a good way to do multiple authors. Am I incorrect? When I create 2 copies and rebuild with one, it sets all the authors to that one.

If its not possible, why is there an author on every post? If every post has the same author, it seems redundant to include it in every post.

**Comment by Justin-Chaschowy** [comment]
Well bash blog was intended for one person to use, so the name is for branding purposes.

But if you wanted to make something bigger with loads of features yourself, you can. I'm working on implementing pagination. Someone earlier made a thread about requesting static pages.

The thing is bashblog was always intended to be a tiny script. I'm not sure Carlos is very interested in adding features.

**Comment by Lex-2008** [comment]
Like we do with post dates (by extracting them from file timestamps, i.e. meta-info), maybe we could use "owner" of file as post author and extract full name from `/etc/passwd` file, like http://stackoverflow.com/questions/833227/whats-the-easiest-way-to-get-a-users-full-name-on-a-linux-posix-system describes?

**Comment by cfenollosa** [comment]
@Justin-Chaschowy is right in that the authorship is just for branding, as supporting multiple authors (with author pages, etc) would complicate the code too much.

@Lex-2008 that is a good idea. Would that be a good solution, @virtualdxs? What do you need, just a variable with the author name? We could try to find a simple solution for that

**Comment by virtualdxs** [comment]
Here's my ideal situation:
Two .sh files: alice.sh and bob.sh
When Alice writes a post she uses alice.sh, which has Alice as the author name
When Bob writes a post he uses bob.sh, which has Bob as the author name
When either posts or rebuilds, the individual post authors are preserved.

**Comment by virtualdxs** [comment]
The only reason I think the passwd solution would not be a good idea is because the full name in passwd may not be the name the author wants to use.

**Comment by cfenollosa** [comment]
Ok, I have something on my mind. Let me work on it for a few days. Thanks for the suggestion!

**Comment by cfenollosa** [comment]
@virtualdxs now `rebuild` keeps the original author name. You can give every user a different `.config` file, and on rebuilding, each post will keep its author.

**Comment by virtualdxs** [comment]
Alright, awesome! Thanks!
